name: liveomok
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pillow
  - pip
  - pip:
    - pygame

# dependencies:
#   - python=3.12.5
#   - numpy=2.0.1
#   - pillow=10.4.0
#   - pip=24.2
#   - pip:
#       - pygame==2.6.0
